# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-23 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20190622_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('Litres', models.CharField(choices=[('40Ltrs', '40Ltrs'), ('60Ltrs', '60Ltrs'), ('80Ltrs', '80Ltrs'), ('100Ltrs', '100Ltrs'), ('120Ltrs', '120Ltrs'), ('140Ltrs', '140Ltrs'), ('160Ltrs', '160Ltrs'), ('180Ltrs', '180Ltrs'), ('200Ltrs', '200Ltrs'), ('300Ltrs', '300Ltrs'), ('1000Ltrs', '1000Ltrs'), ('2000Ltrs', '2000Ltrs'), ('3000Ltrs', '3000Ltrs'), ('4000Ltrs', '4000Ltrs'), ('5000Ltrs', '5000Ltrs'), ('10000Ltrs', '1000Ltrs')], default='40Ltrs', max_length=120)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
